### ISSUE TITLE
Prowlarr Fix

### ISSUE THREAD

**Issue by Kawanaao** [azukaar/cosmos-servapps-official#121]
## What's wrong

Field data is defined as null if you do not specify any data, cosmos tries to import it, which causes an error

## Related lines

https://github.com/azukaar/cosmos-servapps-official/blob/803d9a82b61850423ec78c3daf52a6514500e8d2/servapps/Prowlarr/cosmos-compose.json#L93-L99

## [Related Discord issue](https://discord.com/channels/1083875833824944188/1193418505635246240)

**Comment by azukaar** [comment]
Fixed in 0.14
