### ISSUE TITLE
[Bug] Icon/Screenshot placeholder for applications without one

### ISSUE THREAD

**Issue by arvchristos** [azukaar/cosmos-servapps-official#133]
Trying to set up [imap-filter-proxy](https://github.com/darkphnx/ical-filter-proxy) as a servapp (initially for my personal market), I realized that there is no icon placeholder in case none can be provided, as this project does not have a logo. The same applies for the screenshots. 

For the screenshot case, I saw that there is at least one application that does not provide any, but provides a `.keep` file (https://github.com/azukaar/cosmos-servapps-official/tree/master/servapps/unpackerr/screenshots). This results in a broken include for the Cosmos interface:

![image](https://github.com/azukaar/cosmos-servapps-official/assets/1295367/22d18023-7628-4c16-a7e3-46ec29821456)

What is the suggested solution for cases like this?

I think a good idea would be to add a placeholder both for icons and screenshots.

**Comment by azukaar** [comment]
Something like a simple image with the name of the project can be used as screenshot / logo for example?
