### ISSUE TITLE
Third application market

### ISSUE THREAD

**Issue by vncloudsco** [azukaar/cosmos-servapps-official#75]
We want to build our own set of market libraries that only we can use. What should I do if I want to replace or add to the server when deploying? We need multiple applications and don't want to have to build each component.

**Comment by vncloudsco** [comment]
Can you add customization about personal repository??
https://github.com/azukaar/Cosmos-Server/blob/8a5e261bd10959c072c478952479915672fd2d07/src/market/init.go#L13-L16

**Comment by vncloudsco** [comment]
how to enable 3rd party repo?
```
Why is it called a marketplace instead of app store? In the spirit of selfhosted, I am planning to add the ability for user to add any 3rd party repo they want to their interface to fetch applications from multiple places (it's actually already there, just disabled while the market feature gets stabilized). Let me know if any more questions!

````
ref: https://www.reddit.com/r/selfhosted/comments/14hp3is/cosmos_080_all_in_one_secure_reverseproxy/

**Comment by azukaar** [comment]
You can add entries in MarketConfig.Sources in your config file, but I would recommend waiting until I build a UI for it, as I didn't properly test that functionality yet (Shouldnt be too long)

**Comment by vncloudsco** [comment]
@azukaar  Thank you, we will wait, hopefully it will come one day soon, because I need to deploy many similar servers to many departments so this feature is necessary for us.

**Comment by vncloudsco** [comment]
@azukaar I have seen my server updated with related features, it's great, thank you!

**Comment by azukaar** [comment]
@vncloudsco btw do you have Discord? Would you mind contacting me there?
I wanted to ask you a question or two when you have time :)

**Comment by vncloudsco** [comment]
@azukaar you can contact me via username: ``` tiny_official ```
