### ISSUE TITLE
[App Request] Discourse 

### ISSUE THREAD

**Issue by Stele77** [azukaar/cosmos-servapps-official#81]
Hi!
After years of self hosting, i think Cosmos mission and philosophy is just perfect, and i cant wait to see it mature!

As it is, someone without and IT background like me will find it hard to impossible to integrate non-market "normal" docker apps into Cosmos, while i was able to set them up on a normal Ubuntu server (ofc in a horribly unsafe noob manner....) - But integrating them into Cosmos is where i fail.
I am trying to learn and to figure it out myself, but with the very early stage of the docs, and only one person on YouTube creating 3. party tutorials, that is a big task for a hobbyist like myself, how neverless depends on the apps to work (coming from renting Nextcloud in the cloud as SaaS).

It would be great if the 3 Apps i badly need yould be brought into the store:
-Monica (A personal CRM) https://hub.docker.com/_/monica 10M+ pulls
-OpenProject (Project Management, has the ability to integration with Nextcloud) https://hub.docker.com/r/openproject/community 10M+ pulls
-Discourse (Forum software, has the ability to integration with Nextcloud) https://hub.docker.com/r/bitnami/discourse 10M+ pulls

All apps are very popular with over 10 Million pulls each on docker hub, and would certainly not only help me, but many others.
Thanks in advance for your consideration and your work in general!

PS: I will create individual issues for each app for better issue tracking.

**Comment by vncloudsco** [comment]
If you want to install Discourse, you can use the installation 

https://github.com/TinyActive/cosmos-servapps-official/tree/master/servapps/Discourse
